version: "3"
services:
  api:
    image: node:16
    container_name: api
    working_dir: /app
    command: npm start
    ports:
      - "8000:8000"
    volumes:
      - "./backend/:/app"
  client:
    image: node:16
    container_name: client
    working_dir: /src
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/:/src"
  socket:
    build: ./socket
    container_name: socket
    ports:
      - "4000:4000"
    volumes:
      - "./socket:/app"
